services:
  - type: web
    name: changepreneurship-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app"
    envVars:
      - key: FLASK_ENV
        value: production
